# Consume:
CONSUMER_KEY    = 'XXXXXXXXXXXXXXXXXXXX'
CONSUMER_SECRET = 'YYYYYYYYYYYYYYYYYYYYYYYYYYY'

# Access:
ACCESS_TOKEN  = 'WWWWWWWWWWWWWWWWWWWWWWWWW'
ACCESS_SECRET = 'ZZZZZZZZZZZZZZZZZZZZZZZZ'

MYSELF = 'your_user_name'
